// 第一章〈上層墓道〉：沉默王陵的入口層——收集寶藏、找到青銅鑰匙、打開封門廳。
export const DUNGEON1 = {
  id: 'dungeon1',
  name: '第一章：上層墓道',
  next: 'dungeon2',
  exitNeeds: 'bronzekey',
  exitHint: '下行的石門上了青銅鎖——聽說上一批尋寶人裡有人拿著鑰匙，再也沒走出去',
  spawn: { x: 2.5, z: 2.5, yaw: Math.PI },
  lockNames: { bronzekey: '青銅鑰匙', chapterExit: '下行石門' },
  story: [
    '斷崖底下的霧散開時，江無涯看見了那道石門。\n\n和祖父手繪地圖上畫的一模一樣——「沉默王陵」，無名古王的墓，殉葬品堆成山。\n\n地圖背面是祖父的字：「我進去過。我後悔了。別去。」\n\n可是江家欠的債，不會自己消失。',
    '石門推開的瞬間，一股陳年的冷氣撲面而來，像整座山吐出的一口氣。\n\n火把照亮墓道的第一面壁畫：跪拜的人群、堆積如山的黃金，和一位臉被鑿去的王。\n\n壁畫最底下有一行小字，是後來的人刻上去的——\n\n「拿多少，還多少。」',
    '目標：收集墓道裡的殉葬寶物，找到通往下層的路。\n\n（寶藏會計入結算評價；小心——這座墓裡的「守衛」從來沒有下班。）',
  ],
  endingText: '',
  objective: '收集寶藏，找到青銅鑰匙，打開下行石門',
  rooms: [
    { id: 'entry', name: '陵墓入口', x: 0, z: 0, w: 5, d: 5, h: 3.4, floor: 'stone', walls: 'stone',
      light: { x: 2.5, y: 3, z: 2.5, color: 0xffc080, intensity: 26 } },
    { id: 'stairs', name: '石階廳', x: 5, z: 0, w: 8, d: 6, h: 4, floor: 'stone', walls: 'stone',
      light: { x: 9, y: 3.6, z: 3, color: 0xffb060, intensity: 24, flicker: true } },
    { id: 'gallery', name: '燈火長廊', x: 13, z: 1.5, w: 14, d: 3, h: 3, floor: 'stone', walls: 'stone',
      light: { x: 20, y: 2.6, z: 3, color: 0xff9040, intensity: 18, flicker: true } },
    { id: 'vesselroom', name: '祭器庫', x: 5, z: 6, w: 8, d: 6, h: 3.2, floor: 'stone', walls: 'stone',
      light: { x: 9, y: 2.8, z: 9, color: 0xffc080, intensity: 20, flicker: true } },
    { id: 'muralroom', name: '壁畫室', x: 13, z: 4.5, w: 7, d: 6, h: 3.4, floor: 'stone', walls: 'plaster',
      light: { x: 16.5, y: 3, z: 7.5, color: 0xffd9a0, intensity: 24 } },
    { id: 'wellroom', name: '水井室', x: 20, z: 4.5, w: 7, d: 7, h: 3.6, floor: 'stone', walls: 'stone',
      light: { x: 23.5, y: 3.2, z: 8, color: 0x88aacc, intensity: 14, flicker: true } },
    { id: 'burialpit', name: '殉葬坑', x: 13, z: 10.5, w: 14, d: 8, h: 4.2, floor: 'stone', walls: 'stone',
      light: { x: 20, y: 3.8, z: 14.5, color: 0xff8040, intensity: 22, flicker: true } },
    { id: 'guardroom', name: '守衛室', x: 27, z: 11, w: 6, d: 6, h: 3, floor: 'stone', walls: 'stone',
      light: { x: 30, y: 2.6, z: 14, color: 0xffc080, intensity: 20 } },
    { id: 'sealhall', name: '封門廳', x: 27, z: 3, w: 6, d: 8, h: 4.4, floor: 'stone', walls: 'stone',
      light: { x: 30, y: 4, z: 7, color: 0xcc9955, intensity: 26, flicker: true } },
  ],
  doors: [
    { id: 'g1-entry-stairs', from: 'entry', to: 'stairs', axis: 'z', at: [5, 2.5], width: 1.6, height: 2.6, lock: null },
    { id: 'g1-stairs-gallery', from: 'stairs', to: 'gallery', axis: 'z', at: [13, 3], width: 1.4, height: 2.3, lock: null },
    { id: 'g1-stairs-vessel', from: 'stairs', to: 'vesselroom', axis: 'x', at: [9, 6], width: 1.3, height: 2.2, lock: null },
    { id: 'g1-gallery-mural', from: 'gallery', to: 'muralroom', axis: 'x', at: [16.5, 4.5], width: 1.2, height: 2.2, lock: null },
    { id: 'g1-gallery-well', from: 'gallery', to: 'wellroom', axis: 'x', at: [23.5, 4.5], width: 1.2, height: 2.2, lock: null },
    { id: 'g1-mural-pit', from: 'muralroom', to: 'burialpit', axis: 'x', at: [16.5, 10.5], width: 1.4, height: 2.4, lock: null },
    { id: 'g1-well-pit', from: 'wellroom', to: 'burialpit', axis: 'x', at: [23.5, 11.5], width: 1.3, height: 2.2, lock: null },
    { id: 'g1-pit-guard', from: 'burialpit', to: 'guardroom', axis: 'z', at: [27, 14], width: 1.2, height: 2.2, lock: null },
    { id: 'g1-well-seal', from: 'wellroom', to: 'sealhall', axis: 'z', at: [27, 7], width: 1.4, height: 2.5, lock: 'bronzekey' },
    { id: 'g1-exit', from: 'sealhall', to: null, axis: 'x', at: [30, 3], width: 1.6, height: 2.6, lock: 'chapterExit' },
  ],
  props: [
    { room: 'entry', type: 'crate', x: 0.8, z: 4.2, solid: 0.4 },
    { room: 'entry', type: 'papers', x: 2.5, z: 1.5 },
    { room: 'stairs', type: 'barrel', x: 6, z: 1, solid: 0.35 },
    { room: 'stairs', type: 'barrel', x: 6.9, z: 1.3, solid: 0.35 },
    { room: 'stairs', type: 'chair_fallen', x: 11, z: 4.5, rot: 1.2 },
    { room: 'gallery', type: 'blood', x: 18, z: 3 },
    { room: 'gallery', type: 'papers', x: 22, z: 2.5 },
    { room: 'vesselroom', type: 'shelf', x: 5.35, z: 8, rot: Math.PI / 2, solid: 0.28 },
    { room: 'vesselroom', type: 'shelf', x: 5.35, z: 10.5, rot: Math.PI / 2, solid: 0.28 },
    { room: 'vesselroom', type: 'barrel', x: 12, z: 11, solid: 0.35 },
    { room: 'vesselroom', type: 'crate', x: 11.5, z: 7, solid: 0.4 },
    { room: 'muralroom', type: 'table', x: 16.5, z: 6, solid: 0.5 },
    { room: 'muralroom', type: 'papers', x: 15, z: 8.5 },
    { room: 'wellroom', type: 'barrel', x: 21, z: 5.5, solid: 0.35 },
    { room: 'wellroom', type: 'blood', x: 23.5, z: 8.5 },
    { room: 'wellroom', type: 'crate', x: 26, z: 10.5, solid: 0.4 },
    { room: 'burialpit', type: 'bodybag', x: 15, z: 13, rot: 0.6 },
    { room: 'burialpit', type: 'bodybag', x: 19, z: 16.5, rot: 2.1 },
    { room: 'burialpit', type: 'bodybag', x: 24, z: 12.5, rot: 1.1 },
    { room: 'burialpit', type: 'blood', x: 17, z: 14.5 },
    { room: 'burialpit', type: 'blood', x: 22, z: 15.8 },
    { room: 'burialpit', type: 'crate', x: 14, z: 17, solid: 0.4 },
    { room: 'burialpit', type: 'barrel', x: 25.8, z: 17, solid: 0.35 },
    { room: 'guardroom', type: 'table', x: 30, z: 12.5, solid: 0.5 },
    { room: 'guardroom', type: 'chair_fallen', x: 28.5, z: 15, rot: 0.4 },
    { room: 'guardroom', type: 'bodybag', x: 31.5, z: 15.5, rot: 0.9 }, // 上一批尋寶人
    { room: 'guardroom', type: 'blood', x: 31, z: 15 },
    { room: 'sealhall', type: 'barrel', x: 28, z: 9.5, solid: 0.35 },
    { room: 'sealhall', type: 'barrel', x: 28.9, z: 9.9, solid: 0.35 },
    { room: 'sealhall', type: 'papers', x: 30, z: 5 },
  ],
  documents: [
    {
      id: 'g1-doc-map', title: '祖父的地圖（背面）', x: 2.5, z: 1.7,
      text: '無涯：\n\n如果你真的來了，記住三件事。\n\n一、金子可以拿，「王的東西」不能碰。\n二、聽到骨頭響，往火光多的地方走。\n三、封門廳的鎖是青銅的——鑰匙在守墓人手上。守墓人死了很多年了，但他還在上班。\n\n——祖父',
    },
    {
      id: 'g1-doc-mural', title: '壁畫銘文拓片', x: 16.8, z: 6.2,
      text: '（有人把壁畫下的古文拓印在紙上，旁邊寫著翻譯）\n\n「王不肯死。王命匠人以金為骨、以玉為心，殉者三百，守陵萬年。」\n\n「觸王冠者，代王守陵。」\n\n翻譯的人在最後補了一句：所以那頂王冠還在下面。誰都沒帶出來過。',
    },
    {
      id: 'g1-doc-lastcrew', title: '尋寶人的遺書', x: 31.3, z: 15.8,
      text: '寫給撿到的人：\n\n我們五個人進來，現在剩我一個。鑰匙我拿到了，但我的腿斷了，走不到封門廳。\n\n下面的東西比上面的兇。錢我不要了。\n\n如果你還能走——帶一句話出去，跟我女兒說，爸爸不是去賭錢。\n\n（遺書旁邊放著一把青銅鑰匙）',
    },
  ],
  npcs: [],
  triggers: [
    { id: 'g1-t-stairs', room: 'stairs', text: '石階深處傳來乾燥的、像骨頭互相敲擊的聲音。', sound: 'groan' },
    { id: 'g1-t-pit', room: 'burialpit', text: '殉葬坑——三百人陪王下葬的地方。屍袋在動。', sound: 'groan', alert: true, shake: 0.08 },
    { id: 'g1-t-guard', room: 'guardroom', text: '守衛室。桌上的油燈還是溫的……', },
    { id: 'g1-t-seal', room: 'sealhall', text: '封門廳。青銅門上刻著：「拿多少，還多少。」', shake: 0.05 },
  ],
  entities: {
    pickups: [
      { id: 'g1-p-ammo1', item: 'handgun_ammo', count: 15, x: 4, z: 4 },
      { id: 'g1-p-herb1', item: 'green_herb', count: 1, x: 1, z: 1 },
      { id: 'g1-p-coin1', item: 'treasure_coin', count: 1, x: 8, z: 9.5 },
      { id: 'g1-p-coin2', item: 'treasure_coin', count: 1, x: 11.8, z: 10.8 },
      { id: 'g1-p-shotgun', item: 'shotgun_weapon', count: 1, x: 6, z: 10.5 },
      { id: 'g1-p-shells1', item: 'shotgun_shells', count: 7, x: 6.8, z: 10.8 },
      { id: 'g1-p-gem1', item: 'treasure_gem', count: 1, x: 16.5, z: 6.3 },
      { id: 'g1-p-herb2', item: 'green_herb', count: 1, x: 14, z: 5.2 },
      { id: 'g1-p-coin3', item: 'treasure_coin', count: 1, x: 24.5, z: 6 },
      { id: 'g1-p-blue1', item: 'blue_herb', count: 1, x: 21, z: 10 },
      { id: 'g1-p-idol1', item: 'treasure_idol', count: 1, x: 20, z: 17.2 },
      { id: 'g1-p-coin4', item: 'treasure_coin', count: 1, x: 15.5, z: 16 },
      { id: 'g1-p-gem2', item: 'treasure_gem', count: 1, x: 25.5, z: 13 },
      { id: 'g1-p-ammo2', item: 'handgun_ammo', count: 15, x: 18, z: 12 },
      { id: 'g1-p-key', item: 'bronzekey', count: 1, x: 32.3, z: 13.8 }, // 遺書旁的腰包（與文件保持互動距離）
      { id: 'g1-p-shells2', item: 'shotgun_shells', count: 7, x: 29, z: 12.8 },
      { id: 'g1-p-herb3', item: 'green_herb', count: 1, x: 28, z: 4 },
      { id: 'g1-p-red1', item: 'red_herb', count: 1, x: 31.5, z: 9.5 },
    ],
    enemies: [
      { id: 'g1-e-z1', type: 'zombie', x: 9, z: 3.5 },
      { id: 'g1-e-z2', type: 'zombie', x: 19, z: 2.8 },
      { id: 'g1-e-dog1', type: 'dog', x: 24, z: 3 },
      { id: 'g1-e-spider1', type: 'spider', x: 23, z: 7.5 },
      { id: 'g1-e-spider2', type: 'spider', x: 25.5, z: 9.5 },
      { id: 'g1-e-z3', type: 'zombie', x: 16, z: 13.5 },
      { id: 'g1-e-z4', type: 'zombie', x: 21, z: 15 },
      { id: 'g1-e-z5', type: 'zombie', x: 24.5, z: 16 },
      { id: 'g1-e-dog2', type: 'dog', x: 18, z: 16.5 },
      { id: 'g1-e-lurker1', type: 'lurker', x: 30, z: 7 }, // 封門廳天花板——守墓人
      { id: 'g1-e-z6', type: 'zombie', x: 30.5, z: 13.5 },
    ],
    typewriters: [
      { id: 'g1-tw-entry', x: 0.8, z: 0.8 },
      { id: 'g1-tw-guard', x: 28, z: 11.6 },
    ],
  },
  start: { weapons: [{ id: 'handgun', rounds: 15 }], items: [] },
};
